#!/bin/bash

set -euo pipefail
set -x

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

EXPERIMENT_NAME="${EXPERIMENT_NAME:-qwen2_5_7b_stage2_code_grpo}"
PREV_STAGE_EXPERIMENT_NAME="${PREV_STAGE_EXPERIMENT_NAME:-${STAGE1_EXPERIMENT_NAME:-qwen2_5_7b_stage1_math_grpo}}"
PREV_STAGE_CHECKPOINT_ROOT="${PREV_STAGE_CHECKPOINT_ROOT:-${STAGE1_CHECKPOINT_ROOT:-}}"

EXPERIMENT_NAME="${EXPERIMENT_NAME}" \
PREV_STAGE_EXPERIMENT_NAME="${PREV_STAGE_EXPERIMENT_NAME}" \
PREV_STAGE_CHECKPOINT_ROOT="${PREV_STAGE_CHECKPOINT_ROOT}" \
bash "${ROOT_DIR}/examples/qwen2_5_7b_code_grpo.sh"